name: Build and Deploy

on:
  # this is just for manual invoking of deploy, optional
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build

    environment:
      name: production
      deployment: false

    runs-on: ubuntu-slim

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10

      - name: Set up Node 24
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        env:
          PUBLIC_WEB3FORMS_ACCESS_KEY: ${{ vars.PUBLIC_WEB3FORMS_ACCESS_KEY }}
          PUBLIC_SENTRY_DSN: ${{ vars.PUBLIC_SENTRY_DSN }}
        run: pnpm build

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: build/

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
